use office::docx::elements::{Paragraph, Run, RunContent};
use office::docx::properties::{ParagraphProperties, RunProperties};
use office::docx::Docx;
use office::docprops::{AppProps, CoreProps};
use office::common::relations::Relationships;
use std::path::Path;
use std::collections::HashMap;

fn main() {
    let mut docx = Docx::default();

    // Initialize AppProps and CoreProps
    docx.app_props = Some(AppProps {
        application: Some("Gemini CLI".to_string()),
        app_version: Some("1.0".to_string()),
    });
    docx.core_props = Some(CoreProps {
        title: Some("Generated Document".to_string()),
        creator: Some("Gemini CLI".to_string()),
        description: Some("A document generated by Gemini CLI".to_string()),
        last_modified_by: Some("Gemini CLI".to_string()),
        revision: Some("1".to_string()),
        created: None,
        modified: None,
    });

    // Initialize Relationships for word/_rels/document.xml.rels
    let mut doc_rels_map = HashMap::new();
    doc_rels_map.insert(
        "rId1".to_string(),
        "styles.xml".to_string(),
    );
    doc_rels_map.insert(
        "rId2".to_string(),
        "settings.xml".to_string(),
    );
    doc_rels_map.insert(
        "rId3".to_string(),
        "theme/theme1.xml".to_string(),
    );
    doc_rels_map.insert(
        "rId4".to_string(),
        "fontTable.xml".to_string(),
    );
    docx.relationships = Some(Relationships::new(doc_rels_map));

    let para = Paragraph {
        properties: Some(ParagraphProperties::default()),
        content: vec![Run {
            properties: Some(RunProperties::default()),
            content: vec![RunContent::Text("Hello, world!".to_string())],
            ..Default::default()
        }
        .into()],
        ..Default::default()
    };
    docx.document.body.content.push(para.into());

    let path = Path::new("test_write.docx");
    if let Err(e) = docx.save(path) {
        eprintln!("Failed to save docx file: {}", e);
    } else {
        println!("Docx file saved to: {:?}", path);
    }
}
